name: flight_tracker_and_bookings_ui_app

description: Flutter project of UI design from Themeforest. 
  It is for easy flight bookings and tracking.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  chat_shape:
    git:
      url: git@github.com:kenresoft/chat_shape.git
      ref: master
  fontresoft:
    git:
      url: git@github.com:kenresoft/fontresoft.git
      ref: master
  extensionresoft:
    git:
      url: git@github.com:kenresoft/extensionresoft.git
      ref: master
  cupertino_icons: ^1.0.5
  go_router: ^6.5.7
  flutter_riverpod: ^2.3.5
  fluttertoast: ^8.2.1
  riverpod_annotation: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  #flutter_lints: ^2.0.1
  custom_lint: ^0.3.4
  riverpod_lint: ^1.3.1
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
  riverpod_generator: ^2.2.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
